### ISSUE TITLE
Constants cannot be cfg-gated multiple times

### ISSUE THREAD

**Issue by nox** [bitflags/bitflags#137]

**Comment by sfackler** [comment]
Why not? This seems to work just fine:

```rust
#[macro_use]
extern crate bitflags;

bitflags! {
    struct Flags: u32 {
        #[cfg(target_os = "linux")]
        const FOO = 1;
    }
}

fn main() {
    let _ = Flags::FOO;
}
```

**Comment by nox** [comment]
@sfackler Thanks for the answer, I just realised I misformulated this issue.

This doesn't work:

```rust
#[macro_use]
extern crate bitflags;

bitflags! {
    struct Flags: u32 {
        #[cfg(target_os = "linux")]
        const FOO = 1;
        #[cfg(not(target_os = "linux"))]
        const FOO = 2;
    }
}

fn main() {
    let _ = Flags::FOO;
}
```

I've worked around it doing this:

```rust
bitflags! {
    struct Flags: u32 {
        const FOO = {
            #[cfg(target_os = "linux")] { 1 }
            #[cfg(not(target_os = "linux"))] { 2 }
        };
    }
}
```

**Comment by sfackler** [comment]
Weird!

**Comment by KodrAus** [comment]
It looks like the problem here is our logic that attempts to handle flags that have been cfg'd out. We intentionally omit attributes from flags to ensure they're known to the debug format and the `all` function. Unfortunately this doesn't handle flags where the same flag is defined with different values based on cfg. I haven't quite unpicked _why_ we need the names of all flags to be available, but I think the way we currently do it might just be plain broken given a flag isn't just either present or not, it may have a totally different value.

**Comment by KodrAus** [comment]
It looks like it might actually be a bit of an artefact from pre-associated-const days (how far we’ve come). It might be possible to simplify these now and either avoid the need for those traits or just apply the cfgs to them.
