### ISSUE TITLE
Allow for NonZero flag types

### ISSUE THREAD

**Issue by lcnr** [bitflags/bitflags#169]
To allow for null pointer optimization:

```
bitflags! {
    struct Flags: std::num::NonZeroU8 {
        const A = 0b00000001;
        const B = 0b00000010;
        const C = 0b00000100;
        const D = 0b00001000;
        const E = 0b00010000;
        const F = 0b00100000;
    }
}
```

**Comment by dtolnay** [comment]
The problem is bitflags aren't enums. They are not restricted to the numeric values listed in the definition. In your case for example `A & B` is of type `Flags` and would be zero.

You may be better off defining this type without `bitflags!` and without any of the trait impls that can end up in a zero value.
