### ISSUE TITLE
Pure rust?

### ISSUE THREAD

**Issue by cheako** [bitflags/bitflags#189]
Is this also useful for non-ffi cases?  Is there a better way if one doesn't need compatibility?

**Comment by KodrAus** [comment]
Hi @cheako :wave:

You can definitely use the `bitflags` crate for non-FFI usecases. Anywhere you'd like to capture a combination of switch values and check for their presence is a case for `bitflags`. It just reduces a lot of boilerplate code you'd otherwise have to write since Rust doesn't have language-level support for flags-like enums.
