### ISSUE TITLE
Document why from_bits_unchecked is unsafe

### ISSUE THREAD

**Issue by little-dude** [bitflags/bitflags#200]
Hello,

From the documentation `from_bits_unchecked()` looks like what I need:

> Convert from underlying bit representation, preserving all bits (even those not corresponding to a defined flag).

However the method is `unsafe`, so I'd like to know under which conditions I can safely use it, and what are the risks if I don't use it correctly.

**Comment by KodrAus** [comment]
Hi @little-dude 👋 

We sketched out the reasoning for making `from_bits_unchecked` unsafe [in the original PR](https://github.com/bitflags/bitflags/pull/188#issuecomment-517586059). The reason is that you become responsible for enforcing the flags have a “valid” bit pattern, which is usually enforced by picking some combination of the flags that were supplied by whoever defined the flags type originally. With `from_bits_unchecked` we don’t guarantee what’s in the flags is constrained to patterns allowed by that list. Does that make sense?

That should definitely make its way into the docs in some form!

**Comment by little-dude** [comment]
Hi @KodrAus,

Thank you! The thread you pointed answers my question. I understand the reason for marking this as `unsafe`. I find it a little weird (or maybe _unconventional_ is a better term) to use `unsafe` to warn about potential _logic_ mistakes, instead of memory management mistakes, so I think it worth making it clear in the documentation indeed. I'll try to send a PR this week-end.

Thanks for your time!
