### ISSUE TITLE
`From`/`TryFrom` impls for generated types

### ISSUE THREAD

**Issue by akiekintveld** [bitflags/bitflags#224]
It would be nice if the generated types had conversions to and from the underlying integer type, where the conversion to the underlying type calls `bits`, and the conversion from the underlying type calls either`from_bits_truncate` (if infallible) or `from_bits` (if fallible).

If there is interest in adding this I can make a PR.

**Comment by KodrAus** [comment]
This sounds good to me!

**Comment by KodrAus** [comment]
Just coming back in through some triage. This isn't something we can or necessarily should add to `bitflags` itself, since users can write their own `From` impls, and there isn't a single universally correct implementation to choose. Whether you want to truncate or preserve additional bits is up to the author of the flags type to determine.

I'll go ahead and close this one now as something we won't be directly pursuing, but thanks for the suggestion!
