### ISSUE TITLE
1.3.x contains a breaking change for < 1.46.0 due to reliance on `const if`

### ISSUE THREAD

**Issue by hlb8122** [bitflags/bitflags#255]
https://blog.rust-lang.org/2020/08/27/Rust-1.46.0.html

https://github.com/bitflags/bitflags/blob/main/src/lib.rs#L550-L556

**Comment by taiki-e** [comment]
FYI: MSRV is documented in readme: https://github.com/bitflags/bitflags#rust-version-support

> The minimum supported Rust version is 1.46 due to use of associated constants and const functions.

**Comment by hlb8122** [comment]
Yep, I've noticed the change now.

https://github.com/bitflags/bitflags/commit/afd25d317c0274ac74cbdaccc170c99cfc4e6723#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

I understand there is no consensus on whether changing MSRV is a breaking change theoretically, however in practice this has broken our builds. Forgive me if this comes across as passive aggressive - feel free to close the issue.

**Comment by KodrAus** [comment]
Hi @hlb8122 👋 

I probably could have also called this out in release notes better. I’ll go update them to make sure it’s clear.

Our policy for `bitflags` is to bump the MSRV in minor versions. Unfortunately because we don’t have direct tools for managing MSRVs we end up needing to bump them reactively when either another dependency does or something comes into reach that’s a major improvement for the library. In this case we could have worked around it to maintain compatibility with older compilers, but I’ve erred on the side of keeping the implementation as straightforward as possible, since big macro APIs are already tricky to maintain.

**Comment by hlb8122** [comment]
I understand.

https://github.com/rust-lang/rust/issues/65262 :crossed_fingers:

**Comment by KodrAus** [comment]
In #259 I called out in the changelog that we've bumped our MSRV a bit more prominently. I can't imagine we'll need to do this again for a while, but I'll try remember to call it out the next time we do too.

Thanks for calling this out everyone!
