### ISSUE TITLE
Make generation of `all`/`is_all`/`not` optional

### ISSUE THREAD

**Issue by Rua** [bitflags/bitflags#269]
If the user relies on these functions setting or unsetting certain flags, then adding a new flag to an existing API could be a breaking change. It might activate a new feature that the user didn't want to activate, or even one that isn't compatible with the other flags and therefore triggers an error. Moreover, in the use case I have in mind, these functions don't really make sense; a user would rarely want to activate every possible flag at once. So it would be very useful to me if they could be disabled in some way.

**Comment by KodrAus** [comment]
Hi @Rua! :wave:

I'm a bit hesitant to start introducing too many dials to tune the way flags types are generated. `bitflags` generated types are better for describing sets of attributes that can be combined with set-like operations rather than for domain-specific options builders. In this case you might be better off either defining your own type for your public API that potentially wraps an internal `bitflags` type. That way you can decide what to expose.

**Comment by Rua** [comment]
In standard Rust, structs and enums can have the `#[non_exhaustive]` attribute, which is made specifically for ensuring that users can't use them in ways that could be broken with future updates. What if `bitflags` recognised this attribute too, and omitted these three functions if it's provided? It would introduce no new syntax, and does what the attribute is intended for.

**Comment by KodrAus** [comment]
I've cooled on the idea of piggybacking standard attributes like `#[repr(transparent)]` or `#[non_exhaustive]` with bitflags-specific semantics. It's not that they're a bad idea (they're actually quite reasonable), but puts a significant design burden on the project to consider interactions more rigorously than we currently have need or capacity for, and to maintain those interactions indefinitely.

I think we're best trying to keep the scope of this library limited to flags with set-like operations and allowing users to define their own semantic wrappers that suit their needs.

Thanks for the suggestion @Rua!
