### ISSUE TITLE
Support zerocopy

### ISSUE THREAD

**Issue by qwandor** [bitflags/bitflags#325]
As per #310, for users of bitflags to continue being able to derive [`zerocopy`](https://crates.io/crates/zerocopy) traits on bitflags-generated types, it appears that there will need to be a cargo feature flag to make the internal bitflags types derive the relevant zerocopy traits.

**Comment by KodrAus** [comment]
We should come up with a strategy for supporting these unstable libraries. I've opened #329 to come up with one.

**Comment by KodrAus** [comment]
Having spent some time trying to make `zerocopy` supportable in `bitflags` I've come to the conclusion that we won't be able to directly support any libraries that require custom derives.

I am working on a general solution to this though so that you can partially "eject" your flags definition and can add derives for libraries `bitflags` doesn't directly support without losing all the nice codegen. It [currently looks like this](https://github.com/bitflags/bitflags/issues/348#issuecomment-1535532991).

**Comment by qwandor** [comment]
Thanks for looking into this!

**Comment by KodrAus** [comment]
Thanks for checking this out @qwandor :+1:

As per https://github.com/bitflags/bitflags/pull/326#issuecomment-1550592464, we can now work with `zerocopy` without needing to support it directly in `bitflags`.
