### ISSUE TITLE
messes with dependent crates!

### ISSUE THREAD

**Issue by installgentoo** [bitflags/bitflags#377]
Since 2.3 or so, every time i manually update version in my crate(which sits in my project as a local dependency 'grafix-toolbox = { path = "toolbox", version = "*", ...'), in which binflags is used, i can't build the project, unless i also change a random dependency version to force a complete rebuild. So, for example, i flick bitflags = "*" to "2.3", compile, and then switch it back.

Otherwise binflags errors with duplicate trait implementations in every struct it's used in.

This is a very annoying and strange issue that probably has something to do with your macros. Started in 2.3 methinks.

**Comment by KodrAus** [comment]
Hi @installgentoo :wave:

I'm not too sure what's going on here, it sounds like maybe an incremental compilation issue. We did a trait migration in `2.3.0`, but that shouldn't cause you to end up with multiple versions of the trait, because you should have only a single version of `bitflags` in your tree.

Do you also see this problem if you run a `cargo update` after changing your dependency versions?

**Comment by installgentoo** [comment]
Manually running cargo update fixes the error too.

**Comment by KodrAus** [comment]
I'm not quite sure what happened here, but it's been a while since there was any activity here so I'll go ahead and close this one, but please feel free to re-open it if there's still some issue.
