### ISSUE TITLE
Usage of `serde` field attributes

### ISSUE THREAD

**Issue by flevi29** [bitflags/bitflags#421]
Usage of this: https://serde.rs/field-attrs.html
Is it possible? If so how?

I have added to `Cargo.toml` `bitflags = {version = "2.6.0", features = ["serde"] }`

I get following error:
![image](https://github.com/user-attachments/assets/b136ade5-4b2f-4d35-a3ed-002560416f31)

**Comment by KodrAus** [comment]
Hi @flevi29 :wave:

`bitflags` doesn't recognize `serde`'s field attributes on its flags because it doesn't generate fields for each of its flags. You can use arbitrary names for your flags, but only if you implement them manually, like in this example: https://github.com/bitflags/bitflags/blob/main/examples/macro_free.rs#L13-L38. That unfortunately means you lose the automatic bitwise trait implementations.

If you're trying to write your flags type to support an existing representation then I would consider implementing `Serialize` and `Deserialize` manually and parsing/formatting the data yourself. You may not really want to represent your actions on the wire as a string of exotic names with `|`s between them.

**Comment by flevi29** [comment]
Thanks for the quick reply!

Alright, so that confirms what we were afraid of. Here's the issue on our end: https://github.com/meilisearch/meilisearch/issues/4645
